export const dynamic = "force-dynamic";

export async function GET(request: Request) {
  const res = await fetch(
    "http://k8s.integration.feather-lab.com:32744/filestorepermissions/",
    {
      headers: {
        Authorization:
          "Bearer eyJ4NXQiOiJNell4TW1Ga09HWXdNV0kwWldObU5EY3hOR1l3WW1NNFpUQTNNV0kyTkRBelpHUXpOR00wWkdSbE5qSmtPREZrWkRSaU9URmtNV0ZoTXpVMlpHVmxOZyIsImtpZCI6Ik16WXhNbUZrT0dZd01XSTBaV05tTkRjeE5HWXdZbU00WlRBM01XSTJOREF6WkdRek5HTTBaR1JsTmpKa09ERmtaRFJpT1RGa01XRmhNelUyWkdWbE5nX1JTMjU2IiwidHlwIjoiYXQrand0IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJqcnVpLm9saXZlaXJhbHZlc0BnbWFpbC5jb20iLCJhdXQiOiJBUFBMSUNBVElPTl9VU0VSIiwicm9sZXMiOlsiQXBwbGljYXRpb25cL0ZlYXRoZXJTdXBlclVzZXIiLCJBcHBsaWNhdGlvblwvRmVhdGhlclN5c3RlbUFkbWluaXN0cmF0b3IiLCJBcHBsaWNhdGlvblwvZmVhdGhlcjEiLCJkZXZvcHMiLCJzdWJzY3JpYmVyIiwiYW5hbHl0aWNzIiwiY3JlYXRvciIsImludGVncmF0aW9uX2RldiIsIm9ic2VydmVyIiwicHVibGlzaGVyIiwic3lzdGVtIiwiZXZlcnlvbmUiXSwiaXNzIjoiaHR0cHM6XC9cL2lzLmludGVncmF0aW9uLmZlYXRoZXItbGFiLmNvbTo5NDQ0XC9vYXV0aDJcL3Rva2VuIiwiZ2l2ZW5fbmFtZSI6Impvc2UgcnVpIiwiY2xpZW50X2lkIjoiQm9XN2x4NmwxSU5sTWtqMWtkdjNjQ0JWMGF3YSIsImF1ZCI6IkJvVzdseDZsMUlObE1rajFrZHYzY0NCVjBhd2EiLCJuYmYiOjE3MTU5NDk2NTgsImF6cCI6IkJvVzdseDZsMUlObE1rajFrZHYzY0NCVjBhd2EiLCJzY29wZSI6Im9wZW5pZCIsImV4cCI6MTcxNTk1MzI1OCwiaWF0IjoxNzE1OTQ5NjU4LCJmYW1pbHlfbmFtZSI6Impvc2UgcnVpIiwianRpIjoiZjNmMzJiNmItMTVhMS00MDk4LWJhNTUtNTkwMzhjZmJlMjdlIiwiZW1haWwiOiJqcnVpLm9saXZlaXJhbHZlc0BnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImpydWkub2xpdmVpcmFsdmVzQGdtYWlsLmNvbSJ9.taFpC4OC3h0l7vJZ49T6aDgHVnwi6RipHSYZX7kTt3-mnmYLv2RxVnyhnM3nbcuesLndumxL13psqjUB5LjMv_RsrGuhsiBrQ2X_QA17O_Td1ZBIGbeasXXQ3qhT58-Rl065etMgF8quM2k72c1ckHdA2EJATSUUUKH8pCACGFXUVEcLDLweefi50hmODKgdAMgNl9fTu1s2fny0ISkqYz-TAZFdEj2fpvEJhyRevD_--4JujxvcK4bbnoEnJ4grZqAzuuK0jpCbAnUJMU9pcfJ_14rRr8fxrCrgjXj5qjkiMBI2hX1r1dq4QmmaqluIPjcFPX9bAo-nJklTnpGr4Q",
      },
      method: "GET",
      cache: "force-cache",
    }
  );
  const data = await res.json();
  return new Response(JSON.stringify(data));
}
