export const dynamic = "force-dynamic";

export async function GET(request: Request) {
  const res = await fetch(
    "http://k8s.integration.feather-lab.com:32744/filestorepermissions/",
    {
      headers: {
        Authorization:
          "Bearer eyJ4NXQiOiJNell4TW1Ga09HWXdNV0kwWldObU5EY3hOR1l3WW1NNFpUQTNNV0kyTkRBelpHUXpOR00wWkdSbE5qSmtPREZrWkRSaU9URmtNV0ZoTXpVMlpHVmxOZyIsImtpZCI6Ik16WXhNbUZrT0dZd01XSTBaV05tTkRjeE5HWXdZbU00WlRBM01XSTJOREF6WkdRek5HTTBaR1JsTmpKa09ERmtaRFJpT1RGa01XRmhNelUyWkdWbE5nX1JTMjU2IiwidHlwIjoiYXQrand0IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJqcnVpLm9saXZlaXJhbHZlc0BnbWFpbC5jb20iLCJhdXQiOiJBUFBMSUNBVElPTl9VU0VSIiwicm9sZXMiOlsiQXBwbGljYXRpb25cL0ZlYXRoZXJTdXBlclVzZXIiLCJBcHBsaWNhdGlvblwvRmVhdGhlclN5c3RlbUFkbWluaXN0cmF0b3IiLCJBcHBsaWNhdGlvblwvZmVhdGhlcjEiLCJkZXZvcHMiLCJzdWJzY3JpYmVyIiwiYW5hbHl0aWNzIiwiY3JlYXRvciIsImludGVncmF0aW9uX2RldiIsIm9ic2VydmVyIiwicHVibGlzaGVyIiwic3lzdGVtIiwiZXZlcnlvbmUiXSwiaXNzIjoiaHR0cHM6XC9cL2lzLmludGVncmF0aW9uLmZlYXRoZXItbGFiLmNvbTo5NDQ0XC9vYXV0aDJcL3Rva2VuIiwiZ2l2ZW5fbmFtZSI6Impvc2UgcnVpIiwiY2xpZW50X2lkIjoiQm9XN2x4NmwxSU5sTWtqMWtkdjNjQ0JWMGF3YSIsImF1ZCI6IkJvVzdseDZsMUlObE1rajFrZHYzY0NCVjBhd2EiLCJuYmYiOjE3MTU5NzA5OTgsImF6cCI6IkJvVzdseDZsMUlObE1rajFrZHYzY0NCVjBhd2EiLCJzY29wZSI6Im9wZW5pZCIsImV4cCI6MTcxNTk3NDU5OCwiaWF0IjoxNzE1OTcwOTk4LCJmYW1pbHlfbmFtZSI6Impvc2UgcnVpIiwianRpIjoiYThjZjUwNTAtYjQwNy00Mjk5LWFjZDEtM2RlZWMwNTBhN2UzIiwiZW1haWwiOiJqcnVpLm9saXZlaXJhbHZlc0BnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImpydWkub2xpdmVpcmFsdmVzQGdtYWlsLmNvbSJ9.c6MAjtFbDNRbiXEMt3FE2sK734jQIiCIdhEa_-BRIaD2P5nayDGqjnGdB5hjKVfoPrZ8wsUc8pwofgP-1HVIrdR1hPiCQqtL67wVn84tuMR_qHKilRJxTcB1s4n422S54w3FfwCly_sNkEnGVxDJVc4uBucUOyBZ1Hk1kHht5_L5JyQZHkED8uKtlqEy8EAXsRnP9iCAY6XCtJ9jwCME8bCQryppCdH2hgGN0RF5W9tSd_Gejy7bMpRlhvyAIrXdhwZ3usIwvAIev1f5exXmgDFkclsKqks9OyjbWMfYdE6n1fqYvDctC7MTmVfLdvSZjDgS-GQL-arR-m0iS6uoXQ",
      },
      method: "GET",
      cache: "force-cache",
    }
  );
  const data = await res.json();
  return new Response(JSON.stringify(data));
}
