export const dynamic = "force-dynamic";

export async function GET(request: Request) {
  const serverBaseURL = process.env.FEATHER_OWL_SERVER_SIDE_URL;
  const res = await fetch(`${serverBaseURL}/filestorepermissions/`, {
    headers: {
      Authorization:
        "Bearer eyJ4NXQiOiJNell4TW1Ga09HWXdNV0kwWldObU5EY3hOR1l3WW1NNFpUQTNNV0kyTkRBelpHUXpOR00wWkdSbE5qSmtPREZrWkRSaU9URmtNV0ZoTXpVMlpHVmxOZyIsImtpZCI6Ik16WXhNbUZrT0dZd01XSTBaV05tTkRjeE5HWXdZbU00WlRBM01XSTJOREF6WkdRek5HTTBaR1JsTmpKa09ERmtaRFJpT1RGa01XRmhNelUyWkdWbE5nX1JTMjU2IiwidHlwIjoiYXQrand0IiwiYWxnIjoiUlMyNTYifQ.eyJzdWIiOiJqcnVpLm9saXZlaXJhbHZlc0BnbWFpbC5jb20iLCJhdXQiOiJBUFBMSUNBVElPTl9VU0VSIiwicm9sZXMiOlsiQXBwbGljYXRpb25cL0ZlYXRoZXJTdXBlclVzZXIiLCJBcHBsaWNhdGlvblwvRmVhdGhlclN5c3RlbUFkbWluaXN0cmF0b3IiLCJBcHBsaWNhdGlvblwvZmVhdGhlcjEiLCJkZXZvcHMiLCJzdWJzY3JpYmVyIiwiYW5hbHl0aWNzIiwiY3JlYXRvciIsImludGVncmF0aW9uX2RldiIsIm9ic2VydmVyIiwicHVibGlzaGVyIiwic3lzdGVtIiwiZXZlcnlvbmUiXSwiaXNzIjoiaHR0cHM6XC9cL2lzLmludGVncmF0aW9uLmZlYXRoZXItbGFiLmNvbTo5NDQ0XC9vYXV0aDJcL3Rva2VuIiwiZ2l2ZW5fbmFtZSI6Impvc2UgcnVpIiwiY2xpZW50X2lkIjoiQm9XN2x4NmwxSU5sTWtqMWtkdjNjQ0JWMGF3YSIsImF1ZCI6IkJvVzdseDZsMUlObE1rajFrZHYzY0NCVjBhd2EiLCJuYmYiOjE3MTYwMTgzNzMsImF6cCI6IkJvVzdseDZsMUlObE1rajFrZHYzY0NCVjBhd2EiLCJzY29wZSI6Im9wZW5pZCIsImV4cCI6MTcxNjAyMTk3MywiaWF0IjoxNzE2MDE4MzczLCJmYW1pbHlfbmFtZSI6Impvc2UgcnVpIiwianRpIjoiMmVlMTczMTMtODE5My00MjY0LTg5ODAtY2QyZTk1MWM4NmQzIiwiZW1haWwiOiJqcnVpLm9saXZlaXJhbHZlc0BnbWFpbC5jb20iLCJ1c2VybmFtZSI6ImpydWkub2xpdmVpcmFsdmVzQGdtYWlsLmNvbSJ9.RcEA3Ac96PbZP1b_D0Gy-CAYZTF244FZ6L1O5oTbunZyq6KbhXWAS_cHpcTWHqym4xyOQZ3fpOJdo85YyUS6SzuRUiKTzEEA8Awo0NxmQqjaUvGBtS2CxxUySU1lISBnESZEvBfIKq52BjdL23hrwPP-XP6x6-H-tIdqNuA8IlRYZSndLv76P_lGJoqQv66fb7U0wic2GAm7H7KPaho_vSeIteMZRWDCkl1KTPw0v7mEz3k90-AAtK0tqkA_wGLmwtRZSJ3eJToavRIRY2qEc9MulgoRweyIwpYFCuexGJUu0BcaGJ0mfKzc1iZ1wMoxWCkNw8mCGKqWjZdqZGX3tw",
    },
    method: "GET",
    cache: "force-cache",
  });
  const data = await res.json();
  return new Response(JSON.stringify(data));
}
